name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Install dependencies
        run: go mod tidy

      - name: Run Unit Tests
        run: go test -race -v ./internal/...

      - name: Generate Coverage Report
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./internal/...

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella

  E2E-Tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind
        options: --privileged
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Install dependencies
        run: go mod tidy

      - name: Run E2E Tests
        run: go test -v ./test/e2e/...

  All-Tests:
    runs-on: ubuntu-latest
    needs: [Unit-Tests, E2E-Tests]
    steps:
      - name: All Tests Passed
        run: echo "✅ All tests (unit and e2e) have passed successfully!"
